version: "3.7"
services:

  client:
    env_file: .env
    user: "${USER_ID}:${USER_ID}"
    build:
      context: ./client
      target: dev
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    volumes:
      - ./client:/home/nodejs
      - client_modules:/home/nodejs/node_modules
    networks:
      - frontend

  server:
    env_file: .env
    user: "${USER_ID}:${USER_ID}"
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/home/elixir
      - server_modules:/home/elixir/deps
    networks:
      - frontend
      - backend
    depends_on:
      - database

  database:
    env_file: .env
    image: postgres:10-alpine
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  database:
  client_modules:
  server_modules:
