version: "3.7"
services:

  client:
    env_file: .env
    user: "${USER}:${USER}"
    build:
      context: ./client
      target: dev
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    volumes:
      - ./client:/app
      - client_modules:/app/node_modules
    networks:
      - frontend

  server:
    env_file: .env
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/app
    networks:
      - frontend
      - backend
    depends_on:
      - database

  database:
    env_file: .env
    image: postgres:10-alpine
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  database:
  client_modules:
