version: "3.7"
services:

  client:
    env_file: .env
    build:
      context: ./client
      target: dev
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    volumes:
      - ./client:/app
      - client_modules:/app/node_modules
    networks:
      - frontend

  server:
    env_file: .env
    build:
      context: ./server
      target: dev
    volumes:
      - ./server/:/app
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:

volumes:
  client_modules:
